### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by MariamAlz** [Hamza5/Pipeline-diacritizer#8]
While trying to run this on Colab:

```
!pipeline_diacritizer train --train-data data/train.csv --val-data data/val.csv
```

I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pipeline_diacritizer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pipeline_diacritizer/pipeline_diacritizer.py", line 289, in main
    train(args.train_data, args.val_data, args.iterations, args.weights_dir, args.early_stop)
  File "/usr/local/lib/python3.7/dist-packages/pipeline_diacritizer/pipeline_diacritizer.py", line 105, in train
    model.train(train_data, val_data, iterations, early_stop)
  File "/usr/local/lib/python3.7/dist-packages/pipeline_diacritizer/diacritization_model.py", line 314, in train
    with open(self.get_trigrams_file_path(), 'wb') as vocab_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/pipeline_diacritizer/Tashkeela_params/DiacritizationModel_trigrams.pkl'
```

**Comment by Hamza5** [comment]
Hello, this looks like it is a permission problem because you are installing it in the system Python directly rather than inside a virtual environment as indicated in the [Download and installation wiki page](https://github.com/Hamza5/Pipeline-diacritizer/wiki/Download-and-installation).
